### ISSUE TITLE
Avatar Loading Problems

### ISSUE THREAD

**Issue by SonyUSA** [theepicsnail/Marker#3]
The marker causes my avatar not to load for many people (red t-pose character at +100% loading), and when it does they can't always see the pen mark. It seems to load other models in my account sometimes, too, as they can see my other hand-gesture model animations that don't belong to my pen avatar. Very rarely it works totally fine, but maybe 1 person can't see the pen...

The same avatar loaded to my friends account seems to work more reliably than mine.

**Comment by theepicsnail** [comment]
That really sounds like the vrc servers are just not happy. It 100% can not load other models from your account. If uploading it to your friends account is better then that also suggests it's probably just an upload/vrc issue. 
I would probably try re-uploading (probably detaching so that you get a new blueprint id as well). Also make sure you're using the latest sdk. They've started getting more strict on requiring the latest sdks for uploads!

**Comment by SonyUSA** [comment]
Hmmm you may be right, I detached the blueprint ID and uploaded it again for the third time and it seems to be totally fine now xD I -did- remove the shadow from the pen, but my friend's is still fine so I'm thinking it's the servers.
