### ISSUE TITLE
Monobehavior or namespace Error

### ISSUE THREAD

**Issue by Kokka0426** [theepicsnail/Marker#9]
Unity cannot save due to some error about monobehavior or namespace, please send help.

**Comment by chibiskuld** [comment]
Not being able to save, seems off. Unless you mean, unable to upload to VRC? As for monobehavior and namespace errors, they can occur if you have two objects using the same ClassName or Namespace that are overlapping. Make sure you aren't mixing this with older versions of the marker, and other like versions of the marker. This will cause that problem. It's very difficult to diagnose what exactly the problem is without more details. Please provide more, if you want a more concise answer.
